name: FAstab
channels:
  - https://conda.graylab.jhu.edu
  - conda-forge
  - defaults
  - https://levinthal:paradox@conda.graylab.jhu.edu
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _go_select=2.3.0=cgo
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.2.0=py311h66f275b_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cffi=1.17.1=py311hf29c0ef_0
  - gemmi=0.7.3=py311h85b76c7_2
  - go=1.22.9=hcefc947_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.1.0=h767d61c_5
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.6.0=h26f9b46_0
  - pip=25.0=py311h06a4308_0
  - pycparser=2.22=pyh29332c3_1
  - pypdb=2.4=pyhd8ed1ab_1
  - pyrosetta=2025.06+release.029c6a159b=py311_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.23.0=py311h49ec1c0_3
  - pip:
      - absl-py==2.2.1
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.3.0
      - biopandas==0.5.1
      - biopython==1.85
      - boto3==1.37.21
      - botocore==1.37.21
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses==0.6
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - e3nn==0.5.6
      - einops==0.8.1
      - fair-esm==2.0.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - ghostscript==0.7
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.71.0
      - h5py==3.13.0
      - hydra-core==1.3.2
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lightning==2.5.1
      - lightning-utilities==0.14.2
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - looseversion==1.1.2
      - markdown==3.7
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-collections==1.1.0
      - mmtf-python==1.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.2.0
      - networkx==3.3
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-ml-py==12.575.51
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - packaging==24.2
      - pandas==2.2.3
      - pdb-tools==2.5.0
      - peft==0.15.1
      - pillow==11.1.0
      - platformdirs==4.3.8
      - pluggy==1.5.0
      - ply==3.11
      - prettytable==3.16.0
      - propcache==0.3.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - pycifrw==5.0.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyecharts==2.0.8
      - pygments==2.19.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pytest==8.3.5
      - pytorch-lightning==2.5.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - s3transfer==0.11.4
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - simplejson==3.20.1
      - smmap==5.0.2
      - svgwrite==1.4.3
      - swankit==0.2.4
      - swanlab==0.6.8
      - sympy==1.13.1
      - tape-proteins==0.5
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.1.0+cu118
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.2.0
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - torchmetrics==1.7.0
      - tqdm==4.67.1
      - transformers==4.50.1
      - tree==0.2.4
      - triton==2.1.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.3.0
      - wandb==0.19.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.18.3
